version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      k8s:
        patterns:
          - "k8s.io/*"
      moby-sys:
        patterns:
          - "github.com/moby/sys/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/integration/images"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10